### ISSUE TITLE
Auto-recording multi-view server demo does not started

### ISSUE THREAD

**Issue by snip21** [packetflinger/opentdm#18]
0. q2pro r1861, g_gamemode any, g_record_mvd 1.
1. during the match "vote restart" passed.
2. one player cast "notready".
3. "vote map xxxx" passed.
4. players cast "ready", match started, but %subj%

**Comment by snip21** [comment]
The problem is partially solvable if sv_mvd_maxmaps is 0.
This solution gives rise to another issue:
If match not started again and players left, the recording does not stopping.
As a result, the state of the empty server will be recorded.

**Comment by jar3817** [comment]
sorry, I've been really busy at work lately. I'll try to check this out soon. I do remember when I added this functionality it caused lag that the players complained about. I think it was due to disk latency, but I'm not sure. If you're server runs on an ssd or nvme drive it should matter though.

**Comment by joe0x04** [comment]
Being handled by #22
