### ISSUE TITLE
Auto-recording multi-view server demo does not stopping

### ISSUE THREAD

**Issue by snip21** [packetflinger/opentdm#19]
0. q2pro r1861, g_gamemode 2, g_record_mvd 1.
1. players cast "ready", countdown started.
2. while countdown in progress one player leave, countdown aborted.
3. sv demostatus  "MVD will stop after the current match"
4. the second player also disconnected, match not started, on server nobody present.
5. sv demostatus  "MVD will stop after the current match"

**Comment by joe0x04** [comment]
being handled in #22
